language: php

php:
  - 7.0
  - 7.0.7
  - nightly
  
before_script:
  - pip install --user codecov
  - cd /home/travis/build/mkungla/aframe-php
  - composer install
  - cd /home/travis/build/mkungla/aframe-php/tests

script:
  - phpunit --coverage-clover="../coverage.clover"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - cd "../"
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover coverage.clover
